post_install() {
	echo "-> Minbif can run through xinetd or as a daemon for now."
	if [ ! `grep minbif /etc/group` ]
	then
		groupadd -g 64 minbif &> /dev/null
	fi

	id minbif &> /dev/null || useradd -u 64 -g minbif -d /var/lib/minbif -s /bin/false minbif
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	userdel  minbif &> /dev/null
	groupdel minbif &> /dev/null
}

post_remove() {
	/bin/true
}

op=$1
shift

$op $*
